/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRepositoriesIndexRouteImport } from './routes/_authenticated/repositories/index'
import { Route as AuthenticatedResultsIndexRouteImport } from './routes/_authenticated/results/index'
import { Route as AuthenticatedResultsResultIdRouteImport } from './routes/_authenticated/results/$resultId'
import { Route as AuthenticatedRunsIndexRouteImport } from './routes/_authenticated/runs/index'
import { Route as AuthenticatedRunsRunIdRouteImport } from './routes/_authenticated/runs/$runId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRepositoriesIndexRoute =
  AuthenticatedRepositoriesIndexRouteImport.update({
    id: '/repositories/',
    path: '/repositories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResultsIndexRoute =
  AuthenticatedResultsIndexRouteImport.update({
    id: '/results/',
    path: '/results/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResultsResultIdRoute =
  AuthenticatedResultsResultIdRouteImport.update({
    id: '/results/$resultId',
    path: '/results/$resultId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRunsIndexRoute = AuthenticatedRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunsRunIdRoute = AuthenticatedRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/callback': typeof CallbackRoute
  '/results/$resultId': typeof AuthenticatedResultsResultIdRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/repositories/': typeof AuthenticatedRepositoriesIndexRoute
  '/results/': typeof AuthenticatedResultsIndexRoute
  '/runs/': typeof AuthenticatedRunsIndexRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/results/$resultId': typeof AuthenticatedResultsResultIdRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/repositories': typeof AuthenticatedRepositoriesIndexRoute
  '/results': typeof AuthenticatedResultsIndexRoute
  '/runs': typeof AuthenticatedRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/results/$resultId': typeof AuthenticatedResultsResultIdRoute
  '/_authenticated/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/_authenticated/repositories/': typeof AuthenticatedRepositoriesIndexRoute
  '/_authenticated/results/': typeof AuthenticatedResultsIndexRoute
  '/_authenticated/runs/': typeof AuthenticatedRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/results/$resultId'
    | '/runs/$runId'
    | '/repositories/'
    | '/results/'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/'
    | '/results/$resultId'
    | '/runs/$runId'
    | '/repositories'
    | '/results'
    | '/runs'
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/'
    | '/_authenticated/results/$resultId'
    | '/_authenticated/runs/$runId'
    | '/_authenticated/repositories/'
    | '/_authenticated/results/'
    | '/_authenticated/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repositories/': {
      id: '/_authenticated/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof AuthenticatedRepositoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results/': {
      id: '/_authenticated/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof AuthenticatedResultsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results/$resultId': {
      id: '/_authenticated/results/$resultId'
      path: '/results/$resultId'
      fullPath: '/results/$resultId'
      preLoaderRoute: typeof AuthenticatedResultsResultIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs/': {
      id: '/_authenticated/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthenticatedRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs/$runId': {
      id: '/_authenticated/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AuthenticatedRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedResultsResultIdRoute: typeof AuthenticatedResultsResultIdRoute
  AuthenticatedRunsRunIdRoute: typeof AuthenticatedRunsRunIdRoute
  AuthenticatedRepositoriesIndexRoute: typeof AuthenticatedRepositoriesIndexRoute
  AuthenticatedResultsIndexRoute: typeof AuthenticatedResultsIndexRoute
  AuthenticatedRunsIndexRoute: typeof AuthenticatedRunsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedResultsResultIdRoute: AuthenticatedResultsResultIdRoute,
  AuthenticatedRunsRunIdRoute: AuthenticatedRunsRunIdRoute,
  AuthenticatedRepositoriesIndexRoute: AuthenticatedRepositoriesIndexRoute,
  AuthenticatedResultsIndexRoute: AuthenticatedResultsIndexRoute,
  AuthenticatedRunsIndexRoute: AuthenticatedRunsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
