modules:
  - agents/code-review
  - agents/shared
  - build-config/crd-generator
  - build-config/detekt
  - events
  - k8s/crds
  - server

plugins:
  - //build-config/crd-generator
  - //build-config/detekt