#!/usr/bin/env node
// Generates src/generated/schema.d.ts from the committed OpenAPI contract (api/openapi.yaml).
// `--check` does not write anything; it exits non-zero when the committed file is stale.
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const here = dirname(fileURLToPath(import.meta.url))
const specPath = resolve(here, '../../../../api/openapi.yaml')
const outPath = resolve(here, '../src/generated/schema.d.ts')
const check = process.argv.includes('--check')

const banner = [
  '/**',
  ' * This file was auto-generated by openapi-typescript from api/openapi.yaml.',
  ' * Do not make direct changes to the file; run `pnpm --filter @sift/api-client generate` instead.',
  ' */',
  '',
].join('\n')

const ast = await openapiTS(new URL(`file://${specPath}`), {
  exportType: true,
  rootTypes: false,
  enum: false,
})
const generated = banner + astToString(ast)

if (check) {
  let current = ''
  try {
    current = await readFile(outPath, 'utf8')
  } catch {
    // missing file is reported below as stale
  }
  if (current !== generated) {
    console.error(
      `${outPath} is out of date with ${specPath}.\n` +
        'Run `pnpm --filter @sift/api-client generate` and commit the result.',
    )
    process.exit(1)
  }
  console.log('schema.d.ts is up to date')
} else {
  await mkdir(dirname(outPath), { recursive: true })
  await writeFile(outPath, generated)
  console.log(`wrote ${outPath}`)
}
