settings:
  kotlin:
    version: 2.4.10
    freeCompilerArgs:
      - -Wextra
      - -Xcollection-literals
      - -Xconsistent-data-class-copy-visibility
      - -Xexplicit-context-arguments
      - -Xname-based-destructuring=complete
      - -Xreturn-value-checker=check
    optIns:
      - kotlin.contracts.ExperimentalContracts
      - kotlin.io.path.ExperimentalPathApi
      - kotlin.time.ExperimentalTime
  jvm:
    jdk:
      version: 25
      distributions:
        - temurin
test-settings:
  kotlin:
    powerAssert: enabled
    freeCompilerArgs:
      - -Wallow-returns-result-of



